openapi: 3.0.0

info:
  title: Sample API
  description: Optional multiline or single-line description in [CommonMark](http://commonmark.org/help/) or HTML.
  version: 0.1.9
servers:
  - url: http://api.example.com/v1
    description: Optional server description, e.g. Main (production) server
  - url: http://staging-api.example.com
    description: Optional server description, e.g. Internal staging server for testing

paths:

#id: 'https://standard.open-contracting.org/schema/1__1__5/record-package-schema.json'
#$schema: 'http://json-schema.org/draft-04/schema#'

  /ocds/Tender:
    get:
      summary: "Returns the requested release with supplied OCID"
      operationId: OCDS.Tender   
      parameters:
      - in: query
        name: "OCIDn"
        schema:
          type: string
        example: "dd/mm/yy:hh:mm:ss"
        required: true
        description: "OCID of the required release"
      responses:
        '200':
          description: "Returns a release schema"
          content:
            application/vnd.api+json:
              schema:
                allOf:
                  - $ref: 'https://raw.githubusercontent.com/Crown-Commercial-Service/ccs-api-definitions-common/main/OCDS/OCDS_Vanilla.yaml#/components/schemas/Tender'
                  - $ref: '#/components/schemas/Tender'
        '403':
          $ref: 'https://raw.githubusercontent.com/Crown-Commercial-Service/ccs-scale-api-definitions/BAT_initial/common/CCS_Standard_API_Responses.yaml#/components/responses/403Forbidden'
        '404':
          $ref: 'https://raw.githubusercontent.com/Crown-Commercial-Service/ccs-scale-api-definitions/BAT_initial/common/CCS_Standard_API_Responses.yaml#/components/responses/404NotFound'
        '500':
          $ref: 'https://raw.githubusercontent.com/Crown-Commercial-Service/ccs-scale-api-definitions/BAT_initial/common/CCS_Standard_API_Responses.yaml#/components/responses/500InternalServerError'   



# id: 'https://standard.open-contracting.org/schema/1__1__5/release-package-schema.json'
# $schema: 'http://json-schema.org/draft-04/schema#'

  /ocds/Lot:
    get:
      summary: "Returns a package of releases"
      operationId: OCDS.Document   
      responses:
        '200':
          description: "Returns a release schema"
          content:
            application/vnd.api+json:
              schema:
                allOf:
                  - $ref: 'https://raw.githubusercontent.com/Crown-Commercial-Service/ccs-api-definitions-common/main/OCDS/OCDS_Lot_Ext.yaml#/components/schemas/Lot'
                  - $ref: '#/components/schemas/Lot'
        '403':
          $ref: 'https://raw.githubusercontent.com/Crown-Commercial-Service/ccs-api-definitions-common/main/CCS_OpenAPI_Standards/CCS_Standard_API_Responses.yaml#/components/responses/403Forbidden'
        '404':
          $ref: 'https://raw.githubusercontent.com/Crown-Commercial-Service/ccs-api-definitions-common/main/CCS_OpenAPI_Standards/CCS_Standard_API_Responses.yaml#/components/responses/404NotFound'
        '500':
          $ref: 'https://raw.githubusercontent.com/Crown-Commercial-Service/ccs-api-definitions-common/main/CCS_OpenAPI_Standards/CCS_Standard_API_Responses.yaml#/components/responses/500InternalServerError' 
 
components:
  schemas:
    Tender:
      properties:
        techniques:
          title: Techniques
          description: 'Information about the use of techniques, such as framework agreements, dynamic purchasing systems and electronic auctions.'
          allOf:
            - $ref: '#/components/schemas/Techniques'
            
            
    Lot:
      properties:
        techniques:
          title: Techniques
          description: 'Information about the use of techniques, such as framework agreements, dynamic purchasing systems and electronic auctions.'
          allOf:
            - $ref: '#/components/schemas/Techniques'
            
            
    Techniques:
      title: Techniques
      description: 'Information about the use of techniques, such as framework agreements, dynamic purchasing systems and electronic auctions.'
      type: object
      properties:
        hasFrameworkAgreement:
          title: Framework agreement involved
          description: Whether a framework agreement is involved.
          nullable: true
          type: boolean
        frameworkAgreement:
          title: Framework agreement
          description: Information about the framework agreement.
          allOf:
            - $ref: '#/components/schemas/FrameworkAgreement'
        hasDynamicPurchasingSystem:
          title: Dynamic purchasing system involved
          description: Whether a dynamic purchasing system is involved.
          nullable: true
          type: boolean
        dynamicPurchasingSystem:
          title: Dynamic purchasing system
          description: Information about the dynamic purchasing system.
          allOf:
            - $ref: '#/components/schemas/DynamicPurchasingSystem'
        hasElectronicAuction:
          title: Electronic auction used
          description: Whether an electronic auction is used.
          nullable: true
          type: boolean
        electronicAuction:
          title: Electronic auction
          description: Information about the electronic auction.
          allOf:
            - $ref: '#/components/schemas/ElectronicAuction'
      minProperties: 1
      
      
    FrameworkAgreement:
      title: Framework agreement
      description: Information about the framework agreement.
      type: object
      properties:
        minimumParticipants:
          title: Minimum number of participants
          description: The minimum number of participants in the framework agreement.
          nullable: true
          type: number
        maximumParticipants:
          title: Maximum number of participants
          description: 'The maximum number of participants in the framework agreement. If there is no maximum, set to 1e9999 (which parses to infinity).'
          type: number
        method:
          allOf:
            - $ref: 'https://raw.githubusercontent.com/Crown-Commercial-Service/ccs-api-definitions-common/main/OCDS/OCDS_CodeLists_Ext.yaml#/components/schemas/FrameworkAgreementMethod'
          #openCodelist: false
          #codelist: frameworkAgreementMethod.csv
        periodRationale:
          title: Duration rationale
          description: The justification for exceptional cases when the duration of a framework agreement exceeds the legal limits.
          nullable: true
          type: string
          minLength: 1
        buyerCategories:
          title: Buyer categories
          description: Any additional categories of buyers participating in the framework agreement and not mentioned by name (e.g. 'all hospitals in the Tuscany region').
          nullable: true
          type: string
          minLength: 1
        value:
          title: Value
          description: The total upper estimated value of the framework agreement.
          allOf:
            - $ref: 'https://raw.githubusercontent.com/Crown-Commercial-Service/ccs-api-definitions-common/main/OCDS/OCDS_Vanilla.yaml#/components/schemas/Value'
        period:
          title: Period
          description: The period over which the framework agreement is estimated to be active.
          allOf:
            - $ref: 'https://raw.githubusercontent.com/Crown-Commercial-Service/ccs-api-definitions-common/main/OCDS/OCDS_Vanilla.yaml#/components/schemas/Period'
        description:
          title: Description
          description: A summary description of the framework agreement. This complements any structured information provided using the other fields.
          nullable: true
          type: string
          minLength: 1
      minProperties: 1
      
      
    DynamicPurchasingSystem:
      title: Dynamic purchasing system
      description: Information about the dynamic purchasing system.
      type: object
      properties:
        type:
          allOf:
            - $ref: 'https://raw.githubusercontent.com/Crown-Commercial-Service/ccs-api-definitions-common/main/OCDS/OCDS_CodeLists_Ext.yaml#/components/schemas/DynamicPurchasingSystemType'
          #openCodelist: false
          #codelist: dynamicPurchasingSystemType.csv
        status:
          allOf:
            - $ref: 'https://raw.githubusercontent.com/Crown-Commercial-Service/ccs-api-definitions-common/main/OCDS/OCDS_CodeLists_Ext.yaml#/components/schemas/DynamicPurchasingSystemStatus'
          #openCodelist: false
          #codelist: dynamicPurchasingSystemStatus.csv

      minProperties: 1
      
      
    ElectronicAuction:
      title: Electronic auction
      description: Information about the electronic auction.
      type: object
      properties:
        url:
          title: URL
          description: The internet address of the electronic auction.
          nullable: true
          type: string
          minLength: 1
        description:
          title: Description
          description: Any additional information about the electronic auction.
          nullable: true
          type: string
          minLength: 1
      minProperties: 1