openapi: 3.0.0

info:
  title: OCDS Bid Statistics and details API
  description: For classifying organizations as micro, sme or large.
  version: 0.0.2
servers:
  - url: http://api.example.com/v1
    description: Optional server description, e.g. Main (production) server
  - url: http://staging-api.example.com
    description: Optional server description, e.g. Internal staging server for testing

paths:

#id: 'https://standard.open-contracting.org/schema/1__1__5/record-package-schema.json'
#$schema: 'http://json-schema.org/draft-04/schema#'


  /ocds/Award:
    get:
      summary: "Returns the requested release with supplied OCID"
      operationId: OCDS.Award  
      parameters:
      - in: query
        name: "OCID"
        schema:
          type: string
        example: "dd/mm/yy:hh:mm:ss"
        required: true
        description: "OCID of the required release"
      responses:
        '200':
          description: "Returns a release schema"
          content:
            application/json:
              schema:
                allOf:
                  - $ref: 'https://raw.githubusercontent.com/Crown-Commercial-Service/ccs-api-definitions-common/main/OCDS/OCDS_Vanilla.yaml#/components/schemas/Award'
                  - $ref: '#/components/schemas/Award'

        '403':
          $ref: 'https://raw.githubusercontent.com/Crown-Commercial-Service/ccs-api-definitions-common/main/CCS_OpenAPI_Standards/CCS_Standard_API_Responses.yaml#/components/responses/403Forbidden'
        '404':
          $ref: 'https://raw.githubusercontent.com/Crown-Commercial-Service/ccs-api-definitions-common/main/CCS_OpenAPI_Standards/CCS_Standard_API_Responses.yaml#/components/responses/404NotFound'
        '500':
          $ref: 'https://raw.githubusercontent.com/Crown-Commercial-Service/ccs-api-definitions-common/main/CCS_OpenAPI_Standards/CCS_Standard_API_Responses.yaml#/components/responses/500InternalServerError'   

  /ocds/BidStatistic:
    get:
      summary: "Returns the requested release with supplied OCID"
      operationId: OCDS.BidStatistic  
      parameters:
      - in: query
        name: "OCID"
        schema:
          type: string
        example: "dd/mm/yy:hh:mm:ss"
        required: true
        description: "OCID of the required release"
      responses:
        '200':
          description: "Returns a release schema"
          content:
            application/json:
              schema:
                allOf:
                  - $ref: '#/components/schemas/BidsStatistic'

        '403':
          $ref: 'https://raw.githubusercontent.com/Crown-Commercial-Service/ccs-api-definitions-common/main/CCS_OpenAPI_Standards/CCS_Standard_API_Responses.yaml#/components/responses/403Forbidden'
        '404':
          $ref: 'https://raw.githubusercontent.com/Crown-Commercial-Service/ccs-api-definitions-common/main/CCS_OpenAPI_Standards/CCS_Standard_API_Responses.yaml#/components/responses/404NotFound'
        '500':
          $ref: 'https://raw.githubusercontent.com/Crown-Commercial-Service/ccs-api-definitions-common/main/CCS_OpenAPI_Standards/CCS_Standard_API_Responses.yaml#/components/responses/500InternalServerError' 

  /ocds/Bids:
    get:
      summary: "Returns the requested release with supplied OCID"
      operationId: OCDS.Bids  
      parameters:
      - in: query
        name: "OCID"
        schema:
          type: string
        example: "dd/mm/yy:hh:mm:ss"
        required: true
        description: "OCID of the required release"
      responses:
        '200':
          description: "Returns a release schema"
          content:
            application/json:
              schema:
                allOf:
                  - $ref: '#/components/schemas/Bids'

        '403':
          $ref: 'https://raw.githubusercontent.com/Crown-Commercial-Service/ccs-api-definitions-common/main/CCS_OpenAPI_Standards/CCS_Standard_API_Responses.yaml#/components/responses/403Forbidden'
        '404':
          $ref: 'https://raw.githubusercontent.com/Crown-Commercial-Service/ccs-api-definitions-common/main/CCS_OpenAPI_Standards/CCS_Standard_API_Responses.yaml#/components/responses/404NotFound'
        '500':
          $ref: 'https://raw.githubusercontent.com/Crown-Commercial-Service/ccs-api-definitions-common/main/CCS_OpenAPI_Standards/CCS_Standard_API_Responses.yaml#/components/responses/500InternalServerError'   

  /ocds/Bid:
    get:
      summary: "Returns the requested release with supplied OCID"
      operationId: OCDS.Bid  
      parameters:
      - in: query
        name: "OCID"
        schema:
          type: string
        example: "dd/mm/yy:hh:mm:ss"
        required: true
        description: "OCID of the required release"
      responses:
        '200':
          description: "Returns a release schema"
          content:
            application/json:
              schema:
                allOf:
                  - $ref: '#/components/schemas/Bid'
                  - $ref: 'https://raw.githubusercontent.com/Crown-Commercial-Service/ccs-api-definitions-common/main/OCDS/OCDS_Lot_Ext.yaml#/components/schemas/Bid'
        '403':
          $ref: 'https://raw.githubusercontent.com/Crown-Commercial-Service/ccs-api-definitions-common/main/CCS_OpenAPI_Standards/CCS_Standard_API_Responses.yaml#/components/responses/403Forbidden'
        '404':
          $ref: 'https://raw.githubusercontent.com/Crown-Commercial-Service/ccs-api-definitions-common/main/CCS_OpenAPI_Standards/CCS_Standard_API_Responses.yaml#/components/responses/404NotFound'
        '500':
          $ref: 'https://raw.githubusercontent.com/Crown-Commercial-Service/ccs-api-definitions-common/main/CCS_OpenAPI_Standards/CCS_Standard_API_Responses.yaml#/components/responses/500InternalServerError'   


# id: 'https://standard.open-contracting.org/schema/1__1__5/release-schema.json'
# $schema: 'http://json-schema.org/draft-04/schema#'


components:
  schemas:

    Award:
      properties:
        relatedBid:
          title: Related bid
          description: Where bid details are used, a cross reference to the entry in the bids array to which this award relates. Provide the bid identifier here.
          type: string
          nullable: true

    BidsStatistic:
      title: Bid Statistic
      description: For reporting aggregate statistics about the bids related to a tender. Where lots are in use, statistics can be broken down by lot.
      type: object
      required:
        - id
        - measure
        - value
      properties:
        id:
          title: ID
          description: An internal identifier for this statistic.
          type: string
        measure:
          title: Measure
          description: The statistic reported in the value.
          type: string
          #codelist: bidStatistics.csv
          #openCodelist: true
          #allOf:
          #  - $ref: 'https://raw.githubusercontent.com/Crown-Commercial-Service/ccs-api-definitions-common/main/OCDS/OCDS_CodeLists.yaml#/components/schemas/TenderStatistics'
        date:
          title: Date
          #description: >-
          #  The date when this statistic was last updated. This is often the closing date of the tender process. This field may be omitted unless either (a) the same statistic is provided from multiple points in time, or (b) there is a specific local requirement for the date when statistics were calculated to be provided.
          type: string
          nullable: true
          format: date-time
        value:
          title: Value
          description: >-
            The value for the measure in question. Total counts should be provided as an integer. Percentages should be provided as a proportion of 1 (e.g. 10% = 0.1)
          type: number
        valueGross:
          title: Gross value
          description: The monetary value for the measure in question, including all taxes.
          type: number
          nullable: true
        currency:
          title: Currency
          description: The currency of the amount in the `value` field, if the statistic has a monetary value
          allOf:
            - $ref: 'https://raw.githubusercontent.com/Crown-Commercial-Service/ccs-api-definitions-common/main/OCDS/OCDS_Vanilla.yaml#/components/schemas/Currency'
        notes:
          title: Notes
          description: Any notes needed to understand or interpret the given statistic.
          type: string
          nullable: true
        relatedLot:
          title: Related Lot
          description: Where lots are in use, if this statistic relates to bids on a particular lot, provide the lot identifier here. If left blank, the statistic will be interpreted as applying to the whole tender.
          type: string
          nullable: true

    Bids:
      title: Bids
      description: Summary and detailed information about bids received and evaluated as part of this contracting process.
      type: object
      properties:
        statistics:
          title: Statistics
          description: Summary statistics on the number and nature of bids received. Where information is provided on individual bids, these statistics should match those that can be calculated from the bid details array.
          type: array
          items:
            $ref: '#/components/schemas/BidsStatistic'
        details:
          title: Bid details
          description: An array of bids, providing information on the bidders, and where applicable, bid status, bid values and related documents. The extent to which this information can be disclosed varies from jurisdiction to jurisdiction.
          type: array
          items:
            $ref: '#/components/schemas/Bid'

    Bid:
      title: Bid
      description: For representing a bid in response to the tender or qualification stage in this contracting process.
      type: object
      required:
        - id
      properties:
        id:
          title: ID
          description: A local identifier for this bid
          type: string
        date:
          title: Date
          description: The date when this bid was received.
          type: string
          nullable: true
          format: date-time
        status:
          title: Status
          description: The status of the bid.
          type: string
          nullable: true
          allOf:
            - $ref: 'https://raw.githubusercontent.com/Crown-Commercial-Service/ccs-api-definitions-common/main/OCDS/OCDS_CodeLists.yaml#/components/schemas/TenderStatus'
          #codelist: bidStatus.csv
          #openCodelist: false

        tenderers:
          title: Tenderer
          description: The party, or parties, responsible for this bid.
          type: array
          items:
            $ref: 'https://raw.githubusercontent.com/Crown-Commercial-Service/ccs-api-definitions-common/main/OCDS/OCDS_Vanilla.yaml#/components/schemas/OrganizationReference'
        value:
          title: Value
          description: The total value of the bid.
          allOf:
            - $ref: 'https://raw.githubusercontent.com/Crown-Commercial-Service/ccs-api-definitions-common/main/OCDS/OCDS_Vanilla.yaml#/components/schemas/Value'
        documents:
          title: Documents
          description: All documents and attachments related to the bid and its evaluation.
          type: array
          items:
            $ref: 'https://raw.githubusercontent.com/Crown-Commercial-Service/ccs-api-definitions-common/main/OCDS/OCDS_Vanilla.yaml#/components/schemas/Document'
          uniqueItems: true 