openapi: 3.0.0

components:
  schemas:
    GenericId:
      type: number
      format: integer
      example: 1234
      readOnly: true
      
    OrgId:
      type: string
      example: GB-COH-05684804
      readOnly: true
      
    ContactId:
      type: integer
      format: int32
      readOnly: true
      
    OrgSiteId:
      type: integer
      format: int32
      readOnly: true
      
    UserId:
      type: string
      example: 12345
      readOnly: true
      
    AgreementId:
      type: string
      pattern: RM[1-9]{4}
      example: RM1234
      readOnly: true
      
      
    AgreementVersion:
      type: string
      pattern: V[1-9]{4}
      example: V1
      readOnly: true

    LotId:
      type: string
      example: 1a
      readOnly: true

    AgreementOcid:
      type: string
      pattern: ocds-b5fd17-RM[1-9]{4}
      example: ocds-b5fd17-RM1234
      readOnly: true
      
    ProcurementProjectId:
      type: integer
      example: 123456
      readOnly: true
      
    ProcurementProjectUri:
      type: string
      example: api.crowncommercial.org.uk/tenders/projects/123456
      format: api.crowncommercial.org.uk/tenders/projects/[1-9]+
      readOnly: true  
      
    ProcurementIdList:
      type: array
      items:
        $ref: '#/components/schemas/ProcurementEventID' 
      
    ProcurementEventId:
      type: string
      example: ocds-b5fd17-123456
      pattern: ocds-b5fd17-[1-9]+
      readOnly: true
      
    ProcurementEventReleaseId:
      type: string
      example: ocds-b5fd17-123456-2020-02-16T07:14:54.617Z
      pattern: ocds-b5fd17-[1-9]+-[1-9]{4}-[1-9]{2}-[1-9]{2}T[1-9]{2}:[1-9]{2}:[1-9]{2}.[1-9]{4}
      readOnly: true
      
    Timestamp:
      type: string
      format: date-time
      example: '2020-02-16T07:14:54.617Z'
      readOnly: true
      
    Email:
      type: string
      format: email
      example: support@crowncommercial.org.uk

    DetailFlag:
      type: string
      enum: [full,summary]
      readOnly: true      
      
    TsAndCs:
      type: array
      items:
        $ref: '#/components/schemas/Term'
        
    TermId:
      type: string 
      format: uri
      example: 'http://agreementservice.crowncommercial.gov.uk/agreements/1234/term/1'
  
    Term:
      type: object
      properties:
        id:
          $ref: '#/components/schemas/TermId'
        name:
          type: string
          description: Short name of the term or condition
          example: Modern Slavery
        accepted:
          type: boolean
          example: false
          default: false
        text:
          type: string
          description: Text of the terms and conditions that the user is asked to sign up to
          example: The government’s task force on modern slavery has endorsed a government-wide strategy to tackle this issue. The strategy has identified actions to ensure modern slavery is tackled in government supply chains through public procurement and has committed to publishing its own modern slavery statement in December 2019
          default: ''
        link:
          type: string 
          format: uri
          example: 'http://www.gov.uk/government/publications/uk-government-modern-slavery-statement'
          
    Document:
      allOf:
        -  $ref: 'https://raw.githubusercontent.com/Crown-Commercial-Service/ccs-api-definitions-common/main/CCS_OCDS_Standards/CCS-OCDS_Schema.yaml#/components/schemas/Document'
     # type: object
     # properties:
     #   url:
     #     type: string
     #     format: uri
     #     description: URI for the document. Should be a perma-link and can be used as a key for the document
     #   name:
     #     type: string
     #     description: document name
     #   version:
     #     type: string
     #     description: Version number of the document - does not proscribe the format
     #   documentType:
     #     type: string
     #     description: The type of document e.g. overview, t&cs, guidance, how to buy, contract notice etc

    Errors:
      type: object
      properties:
        errors:
          type: array
          items:
            $ref: '#/components/schemas/Error'
            
    Error:
      type: object
      properties:
        status:
          type: string
        title:
          type: string
        detail:
          type: string
          
    Links:
      allOf:
        -  $ref: 'https://raw.githubusercontent.com/Crown-Commercial-Service/ccs-api-definitions-common/main/OCDS/OCDS_Pagination_Ext.yaml#/components/schemas/Links'
      type: object
      properties:
        self:
          type: string
          format: uri
          description: URL to the current page of the listing
        next:
          description: URL to the next page of the listing
        prev:
          description: URL to the previous page of the listing
        last:
          type: string
          format: uri
          description: URL to the last page of the listing
        first:
          type: string
          format: uri
          description: URL to the first page of the listing
          
    LanguageID:
      $ref: 'https://raw.githubusercontent.com/Crown-Commercial-Service/ccs-api-definitions-common/main/CCS_OCDS_Standards/CCS-OCDS_CodeLists.yaml#/components/schemas/Language'

          

          
          

